INSERT INTO `hiddentourismnode`.`administrator` (`IDADMINISTRATOR`, `FIRSTNAMEADMINISTRATOR`, `LASTNAMEADMINISTRATOR`, `PASSWORDADMINISTRATOR`, `USERADMINISTRATOR`, `EMAILADMINISTRATOR`) 
VALUES ('1727791731', 'Jose', 'Ramirez', 'holamundo', 'jose12', 'jose@hotmail.com');
INSERT INTO `hiddentourismnode`.`administrator` (`IDADMINISTRATOR`, `FIRSTNAMEADMINISTRATOR`, `LASTNAMEADMINISTRATOR`, `PASSWORDADMINISTRATOR`, `USERADMINISTRATOR`, `EMAILADMINISTRATOR`) 
VALUES ('1707461834', 'Manuela', 'Caiza', 'query123', 'manu45', 'manuela@gmail.com');
INSERT INTO `hiddentourismnode`.`administrator` (`IDADMINISTRATOR`, `FIRSTNAMEADMINISTRATOR`, `LASTNAMEADMINISTRATOR`, `PASSWORDADMINISTRATOR`, `USERADMINISTRATOR`, `EMAILADMINISTRATOR`) 
VALUES ('1700773888', 'Kevin', 'Cruz', 'mayo254', 'kev78', 'kev@outlook.com');
INSERT INTO `hiddentourismnode`.`administrator` (`IDADMINISTRATOR`, `FIRSTNAMEADMINISTRATOR`, `LASTNAMEADMINISTRATOR`, `PASSWORDADMINISTRATOR`, `USERADMINISTRATOR`, `EMAILADMINISTRATOR`) 
VALUES ('1794652153', 'Sebastian', 'Peralbo', 'papas125', 'sebas02', 'sebas@gmail.com');
INSERT INTO `hiddentourismnode`.`administrator` (`IDADMINISTRATOR`, `FIRSTNAMEADMINISTRATOR`, `LASTNAMEADMINISTRATOR`, `PASSWORDADMINISTRATOR`, `USERADMINISTRATOR`, `EMAILADMINISTRATOR`) 
VALUES ('1789632014', 'Lucia', 'Martinez', 'tijera154', 'luci789', 'lucia@hotmail.com');
INSERT INTO `hiddentourismnode`.`administrator` (`IDADMINISTRATOR`, `FIRSTNAMEADMINISTRATOR`, `LASTNAMEADMINISTRATOR`, `PASSWORDADMINISTRATOR`, `USERADMINISTRATOR`, `EMAILADMINISTRATOR`) 
VALUES ('1744110025', 'Miguel', 'Bose', 'regla785', 'miguel444', 'miguel2@hotmail.com');
INSERT INTO `hiddentourismnode`.`administrator` (`IDADMINISTRATOR`, `FIRSTNAMEADMINISTRATOR`, `LASTNAMEADMINISTRATOR`, `PASSWORDADMINISTRATOR`, `USERADMINISTRATOR`, `EMAILADMINISTRATOR`) 
VALUES ('1748963025', 'Dario', 'Vera', 'lana478', 'dario325', 'dario1@gmail.com');
INSERT INTO `hiddentourismnode`.`administrator` (`IDADMINISTRATOR`, `FIRSTNAMEADMINISTRATOR`, `LASTNAMEADMINISTRATOR`, `PASSWORDADMINISTRATOR`, `USERADMINISTRATOR`, `EMAILADMINISTRATOR`) 
VALUES ('1702563958', 'Diego', 'Molina', 'papel252', 'diego741', 'diego@gmail.com');
INSERT INTO `hiddentourismnode`.`administrator` (`IDADMINISTRATOR`, `FIRSTNAMEADMINISTRATOR`, `LASTNAMEADMINISTRATOR`, `PASSWORDADMINISTRATOR`, `USERADMINISTRATOR`, `EMAILADMINISTRATOR`) 
VALUES ('1745236985', 'Teresa', 'Guerra', 'goma874', 'tere412', 'tere25@gmail.com');
INSERT INTO `hiddentourismnode`.`administrator` (`IDADMINISTRATOR`, `FIRSTNAMEADMINISTRATOR`, `LASTNAMEADMINISTRATOR`, `PASSWORDADMINISTRATOR`, `USERADMINISTRATOR`, `EMAILADMINISTRATOR`) 
VALUES ('1798563201', 'Julio', 'Jaramillo', 'cinta887', 'julio12', 'julio@outlook.com');